### ISSUE TITLE
Build error on android kotlin

### ISSUE THREAD

**Issue by kelvinkioko** [robertvazan/sourceafis-java#36] opened 2021-01-24 08:22 UTC
Getting this issue "com.android.tools.r8.errors.b: One or more instruction is preventing default interface method from being desugared: java.lang.Double it.unimi.dsi.fastutil.objects.Reference2DoubleMap.getOrDefault(java.lang.Object, java.lang.Double)" on android kotlin when I try to build the project or generate an APK

**Comment by robertvazan** [comment] 2021-01-24 12:20
I will have to find time to reproduce this. Meantime please use version 3.10.0, which was tested on Android.

**Comment by kelvinkioko** [comment] 2021-01-24 17:56
Are there any min sdk, target sdk and compile sdk requirements with version 3.10.0?

I switched to version 3.10.0 and the error is still the same. Doing this on an empty project with no other libraries.

**Comment by robertvazan** [comment] 2021-01-24 18:10
Android API level 24+

**Comment by kelvinkioko** [comment] 2021-01-24 18:13
Works on debug runs but project build or APK generation still fails with this error
`AGPBI: {"kind":"error","text":"com.android.tools.r8.errors.b: One or more instruction is preventing default interface method from being desugared: java.lang.Object it.unimi.dsi.fastutil.ints.Int2ObjectMap.getOrDefault(java.lang.Object, java.lang.Object)","sources":[{"file":"C:\\Users\\Kelvin\\.gradle\\caches\\transforms-2\\files-2.1\\21ba6f848e0139c51edc78af2f0d9e47\\jetified-fastutil-8.3.0.jar"}],"tool":"R8"}`

**Comment by robertvazan** [comment] 2021-01-24 18:20
This is similar to [fastutil #136](https://github.com/vigna/fastutil/issues/136), which is caused by a [bug in desugar](https://issuetracker.google.com/issues/157806261), which should be fixed by now. Try upgrading your Android toolchain.

**Comment by kelvinkioko** [comment] 2021-01-24 18:56
Thank you very much for the assistance. You are a life saver

**Closed** 2021-01-24 18:57 UTC
