### ISSUE TITLE
Error on caching Fingerprint template

### ISSUE THREAD

**Issue by sergioluc** [robertvazan/sourceafis-java#26] opened 2020-03-16 08:27 UTC
Hi!! I want to cache the fingerprint template by serializing it with:
` FingerprintTemplate probe = new FingerprintTemplate(
                new FingerprintImage()
                        .dpi(500)
                        .decode(Files.readAllBytes(Paths.get("src/image/101_1.tif"))));

        byte [] template=probe.toByteArray();`
But following errors appears:
`Exception in thread "main" java.lang.ExceptionInInitializerError
	at JsonTemplate.<init>(JsonTemplate.java:15)
	at FingerprintTemplate.toByteArray(FingerprintTemplate.java:264)
	at MainClass.main(MainClass.java:14)
Caused by: java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2440)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1084)
	at FingerprintCompatibility.lambda$static$0(FingerprintCompatibility.java:37)
	at com.machinezoo.noexception.CheckedExceptionHandler.run(CheckedExceptionHandler.java:1408)
	at FingerprintCompatibility.<clinit>(FingerprintCompatibility.java:35)
	... 3 more
`

The code in MainClass line 14 is:
 `byte [] template=probe.toByteArray();`

**Comment by robertvazan** [comment] 2020-03-16 12:00
File "version.txt" is missing from library's resources. How did you include SourceAFIS in your application? Do you use maven or other dependency management?

**Comment by sergioluc** [comment] 2020-03-16 12:44
I'm using ".jar" for the dependency management

**Comment by sergioluc** [comment] 2020-03-16 12:57
I've fixed the problem by adding "version.txt". Thank you

**Comment by robertvazan** [comment] 2020-03-16 13:23
JAR includes the resource file, so you probably misconfigured it. Anyway, even if you configured resources right, you would be missing dependencies (gson, ...). Please use proper dependency management tool.

Closing this as it's not a bug in SourceAFIS.

**Closed by robertvazan** 2020-03-16 13:23 UTC
